server:
  port: 4000

spring:
  application:
    name: patient-service

  h2:
    console:
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: root123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    root: info
